import { StimuliDataWithIds } from "../../types/stimuli";

export const testStimuliData: StimuliDataWithIds = {
  locale: {
    localeKey: "East Brunswick",
    upperLocale: "New Jersey",
  },
  longRationale: [],
  timestamp: new Date(),
  averageDirt: 0.7,
  rationale:
    "Between November 2, 2023 and November 2, 2025, Easton, Pennsylvania has seen numerous public records—spanning zoning approvals, infrastructure upgrades, redevelopment plans, and housing initiatives—that substantially affect the local real estate market. These events include approvals for major residential and mixed-use projects (The Marquis, The Confluence, The Lynden, senior housing, and a proposed warehouse), park improvements, pedestrian safety upgrades, and environmental remediation efforts. Collectively, these records reflect significant shifts in housing supply, urban revitalization, infrastructure quality, and development capacity—material factors influencing property values, investment appeal, and neighborhood dynamics.",
  stimuli: [
    {
      title: "The Marquis opens in downtown Easton",
      desc: "Mixed‑use residential tower with 264 luxury apartments, retail, garage, rooftop amenities opens in May 2025.",
      date: new Date(),
      coordinates: [0, 0],
      apprStatus: "approved",
      stimType: "New Developments",
      dirtIndex: 0.9,
      url: "https://www.citycentergrp.com/select-recognition/project-three-8zgh7-drk7g-g8smn",
      _id: "432432423423",
    },
    {
      title: "The Confluence approved (opens in 2026)",
      desc: "274‑unit mixed‑use development at river confluence approved and under construction, opening summer 2026.",
      date: new Date(),
      coordinates: [0, 0],
      apprStatus: "approved",
      stimType: "New Developments",
      dirtIndex: 0.9,
      url: "https://www.citycentergrp.com/select-recognition/project-three-8zgh7-drk7g-g8smn",
      _id: "432432423423",
    },
    {
      title: "The Lynden condo project announced",
      desc: "First major condominium development in Lehigh Valley in nearly 25 years, includes residential units and Fidelity Bank retail.",
      date: new Date(),
      coordinates: [0, 0],
      apprStatus: "pending",
      stimType: "New Developments",
      dirtIndex: 0.85,
      url: "https://lvb.com/condo-project-coming-to-downtown-easton/",
      _id: "432432423423",
    },
    {
      title: "45‑unit senior affordable housing approved",
      desc: "Easton Housing Authority granted variances to build 45 affordable one‑bedroom senior apartments at former Easton Home site.",
      date: new Date(),
      coordinates: [0, 0],
      apprStatus: "approved",
      stimType: "Property Assessments",
      dirtIndex: 0.8,
      url: "https://www.lehighvalleynews.com/easton/45-unit-senior-apartment-facility-clears-hurdle-at-former-easton-home-site",
      _id: "432432423423",
    },
    {
      title: "Easton Commerce Center warehouse proposal",
      desc: "Proposal for 1 million‑sq‑ft warehouse at former Pfizer Pigments site—environmental, traffic, flood concerns.",
      date: new Date(),
      coordinates: [0, 0],
      apprStatus: "pending",
      stimType: "Infrastructure",
      dirtIndex: 0.7,
      url: "https://lehighdaily.com/easton-warehouse-renderings-reveal-1-million-square-foot-giant-sparking-community-uproar/",
      _id: "432432423423",
    },
    {
      title: "VM Development Easton Iron & Metal site remediation agreement",
      desc: "Agreement executed Oct 2024 for mixed‑use redevelopment (~200 residential units + 10,000 sq ft commercial + public park link).",
      date: new Date(),
      coordinates: [0, 0],
      apprStatus: "approved",
      stimType: "New Developments",
      dirtIndex: 0.85,
      url: "https://www.easton-pa.com/541/Special-Projects",
      _id: "432432423423",
    },
    {
      title: "Pedestrian safety improvements on Cattell Street",
      desc: "Completed curb bump‑outs, lighting, flashing beacons, sidewalks between College Ave and High Street.",
      date: new Date(),
      coordinates: [0, 0],
      apprStatus: "approved",
      stimType: "Infrastructure",
      dirtIndex: 0.3,
      url: "https://www.easton-pa.com/541/Special-Projects",
      _id: "432432423423",
    },
    {
      title: "Downtown Easton transformation recognized",
      desc: "Easton awarded 2025 Commercial Real Estate Development Award; over $460M private investment since 2021.",
      date: new Date(),
      coordinates: [0, 0],
      apprStatus: "approved",
      stimType: "Macro-Economic",
      dirtIndex: 0.6,
      url: "https://www.lehighvalley.org/news/news-releases/lehigh-valley-successes-and-opportunities-highlighted-easton-s-transformation-honored-at-annual-real-estate-outlook/",
      _id: "432432423423",
    },
    {
      title: "City park improvements completed/upcoming",
      desc: "Upgrades to Vanderveer Park (completed), Centennial Park (underway), Scott Park, Jackson Street, 7th St. Park.",
      date: new Date(),
      coordinates: [0, 0],
      apprStatus: "approved",
      stimType: "Infrastructure",
      dirtIndex: 0.4,
      url: "https://www.easton-pa.com/541/Special-Projects",
      _id: "432432423423",
    },
    {
      title: "Road traffic funding shortfall identified",
      desc: "Lehigh Valley road projects over 25 years underfunded by ~$2.5 billion—transportation pressure growing.",
      date: new Date(),
      coordinates: [0, 0],
      apprStatus: "approved",
      stimType: "Macro-Economic",
      dirtIndex: 0.5,
      url: "https://www.reddit.com/r/lehighvalley/comments/1jhy5o5",
      _id: "432432423423",
    },
  ],
};
